### ISSUE TITLE
Odex

### ISSUE THREAD

**Issue by MrDarkLord** [DavidPisces/MIUI-Auto-Odex#8]
This tool Not Working On mi cc9e eu rom anytings not change
i want to odex my rom thank you for your work

**Comment by DavidPisces** [comment]
What happened when you try to odex your rom?
Have you installed busybox before you use this script?

**Comment by DavidPisces** [comment]
Please provide a screenshot of the execution error to help me identify the problem

**Comment by zjw2017** [comment]
Please check whether there is oat folder in any app directory under / system / APP, or search for ODEX files. If so, it means success, otherwise it fails
